In [2]:
# Python3 implementation of the approach 
N = 100000

# To keep correct and reverse direction 
gr1 = {}; gr2 = {}; 

vis1 = [0] * N; vis2 = [0] * N; 

# Function to add edges 
def Add_edge(gr1, u, v):
	if u not in gr1:
		gr1[u] = []
	gr1[u].append(v)

# DFS function 
def dfs1(x) : 
	vis1[x] = True;
	if x not in gr1 :
		gr1[x] = {};
		
	for i in gr1[x] :
		if (not vis1[i]) :
			dfs1(i) 

# DFS function 
def dfs2(x) : 

	vis2[x] = True; 

	if x not in gr2 :
		gr2[x] = {};
		
	for i in gr2[x] : 
		if (not vis2[i]) :
			dfs2(i); 

def Is_Connected(n) : 

	global vis1;
	global vis2;
	
	# Call for correct direction
	vis1 = [False] * len(vis1);
	dfs1(1);
	
	# Call for reverse direction
	vis2 = [False] * len(vis2);
	dfs2(1);
	
	for i in range(1, n + 1) :
		
		# If any vertex it not visited in any direction
		# Then graph is not connected
		if (not vis1[i] and not vis2[i]) :
			return False;
			
	# If graph is connected
	return True; 

# Driver code 
if __name__ == "__main__" : 

	n = 4; 

	# Add edges 
	Add_edge(1, 2)
	Add_edge(1, 3)
	Add_edge(2, 3)
	Add_edge(3, 4)

	# Function call 
	if (Is_Connected(n)) :
		print("Yes"); 
	else :
		print("No"); 

# This code is contributed by AnkitRai01


No


In [2]:
import modules.ioGLNet as io
import modules.GLNetEISimLib as glsim

In [6]:
import numpy
import random

#pythran export generate_random_net_fixed_input(int,int,int,int)
def generate_random_net_fixed_input(K_ex,pN,K,N):
    """
    ##################
    #BUILD RANDOM NETWORK WITH constant k_in neighbors
    #Neurons cannot have repeated neighbors
    ##################
    returns list C where each entry is the list of neighbor indices:
    C[i] -> list of neighbors of i;
    C[i][:K_ex] -> excitatory neighbors (indices go from 0 to pN); C[i][K_ex:] -> inhibitory neighbors (indices go from 0 to qN)

    K_ex -> number of excitatory inputs
    pN -> total number of excitatory inputs
    K -> total number of inputs
    N -> total number of neurons in the network
    """
    return numpy.array([sorted(random.sample(range(pN),K_ex)) + sorted(random.sample(range(N-pN),K-K_ex)) for _ in range(N)])

C = generate_random_net_fixed_input(7,80,10,100)

C


array([[ 3, 10, 11, 56, 60, 63, 68,  0,  9, 17],
       [ 3,  7, 28, 31, 42, 49, 50,  0,  2, 11],
       [44, 46, 51, 59, 66, 73, 76,  1, 11, 15],
       [ 2,  7, 37, 42, 54, 56, 64,  6,  8, 15],
       [ 6,  7,  9, 14, 29, 30, 74,  0,  5, 15],
       [11, 21, 30, 32, 42, 59, 66,  1,  3, 14],
       [ 3, 21, 26, 55, 61, 62, 63,  0,  2,  4],
       [ 1, 17, 44, 52, 60, 61, 74,  1, 10, 12],
       [ 5, 14, 16, 25, 38, 41, 55,  3, 12, 17],
       [11, 12, 20, 26, 34, 70, 73, 13, 15, 19],
       [ 2, 30, 31, 40, 41, 55, 64, 11, 16, 18],
       [ 2, 21, 31, 35, 54, 56, 76,  2, 10, 15],
       [ 2, 21, 29, 33, 45, 66, 75,  6, 11, 17],
       [ 4, 12, 28, 48, 61, 69, 71,  2,  9, 12],
       [11, 23, 42, 44, 60, 74, 78,  7, 12, 18],
       [10, 12, 22, 47, 60, 66, 73,  2,  7, 18],
       [10, 34, 59, 62, 64, 77, 79,  1, 14, 19],
       [ 3,  6,  7,  8, 11, 55, 61,  1,  7, 18],
       [ 5,  9, 17, 29, 35, 37, 46, 14, 18, 19],
       [12, 32, 35, 55, 58, 67, 69,  4,  9, 15],
       [ 9, 12, 16, 

In [1]:
import sys
import argparse
import modules.ioGLNet as io
import modules.GLNetEISimLib_numba as glsim

sys.argv = 'GLNetEI.py -mu 0.0 -Gamma 0.2 -J 10.0 -g 1.4 -Y 1.0 -theta 1.0 -N 1000 -simType aval -p 0.8 -tTotal 10000 -tTrans 3000 -outputFile run/output/glei_aval_G0.2_g1.4_Y1_N1000.mat -nNeuSpikingData 1000'.split(' ')

parser = argparse.ArgumentParser(description='Simulates a GL network of Excitatory/Inhibitory elements in the mean-field level')
parser = io.add_neuron_params(parser)
args = parser.parse_args()

simParam = io.get_sim_param_struct_for_pythran(args)
print(simParam)

structtype(A=73.5, Gamma=0.2, I=1.0, Iext=0.0, J=10.0, K=10, N=1000, Tmax=10000, VE0=0.0, VE0Std=0.0, VI0=0.0, VI0Std=0.0, XE0=0.0, XE0Rand=True, XI0=0.0, XI0Rand=True, Y=1.0, exc_only_dynthresh=False, fXE0=0.5, fXI0=0.5, g=1.4, mu=0.0, nNeuronsSpk=1000, netType='mf', outputFile='run/output/glei_aval_G0.2_g1.4_Y1_N1000.mat', p=0.8, paramCV=0.0, q=0.19999999999999996, rPoisson=0.0, saveSpikingData=False, saveTxtFile=False, simType='aval', spkFileName='', tTrans=3000, tauT=100.0, tauW=100.0, theta=1.0, uT=0.1, uW=0.1, weightDynType='none', writeOnRun=False)


In [2]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

simParam_str, simParam_types = io.simParam_to_str_for_pythran(simParam),io.get_arg_types_dict(simParam)

print(simParam_str)
print(simParam_types)

simParam_str_nb, simParam_types_nb = glsim.convert_simParam_to_numba_dict(simParam_str, simParam_types)

a = glsim.get_system_parameters(simParam_str_nb, simParam_types_nb)
print(a)

{'mu': '0.0', 'Gamma': '0.2', 'J': '10.0', 'g': '1.4', 'Y': '1.0', 'Iext': '0.0', 'A': '73.5', 'tauW': '100.0', 'uW': '0.1', 'tauT': '100.0', 'uT': '0.1', 'theta': '1.0', 'N': '1000', 'p': '0.8', 'rPoisson': '0.0', 'tTrans': '3000', 'VE0': '0.0', 'VI0': '0.0', 'VE0Std': '0.0', 'VI0Std': '0.0', 'XE0': '0.0', 'XI0': '0.0', 'fXE0': '0.5', 'fXI0': '0.5', 'paramCV': '0.0', 'K': '10', 'outputFile': 'run/output/glei_aval_G0.2_g1.4_Y1_N1000.mat', 'netType': 'mf', 'simType': 'aval', 'weightDynType': 'none', 'saveSpikingData': 'False', 'exc_only_dynthresh': 'False', 'writeOnRun': 'False', 'saveTxtFile': 'False', 'I': '1.0', 'XE0Rand': 'True', 'XI0Rand': 'True', 'q': '0.19999999999999996', 'Tmax': '10000', 'nNeuronsSpk': '1000', 'spkFileName': ''}
{'mu': 'float', 'Gamma': 'float', 'J': 'float', 'g': 'float', 'Y': 'float', 'Iext': 'float', 'A': 'float', 'tauW': 'float', 'uW': 'float', 'tauT': 'float', 'uT': 'float', 'theta': 'float', 'N': 'int', 'p': 'float', 'rPoisson': 'float', 'tTrans': 'int', 

In [3]:
import numpy
import itertools

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

print(glsim.get_stim_neuron_index_aval(60))
print(glsim.multvecelem(numpy.array([1,2,3]),numpy.array([4,5,6])))
print(glsim.PoissonProcess_firingprob(1e-5))
print(glsim.save_spk_data_fake(numpy.empty((0,2),dtype=numpy.int64),2,3))
print(glsim.save_spk_data(numpy.empty((0,2),dtype=numpy.int64),2,3))
print(glsim.save_initial_spkdata(numpy.array([0,1,1,0]),numpy.array([1,0,0,1]),4,4))
W             = 1.0
A             = 1.0
tauWinv       = 10.0
uW            = 0.1
rhoE          = 0.4
rhoI          = 0.4
V             = 1.1
X             = 0.0
synapticInput = 0.0
Iext          = 0.0
mu            = 0.0
theta         = 1.0
Gamma         = 0.2
I             = 1.0
P_poisson     = 0.5
tauTinv       = 10.0
uT            = 0.1
W_I           = 1.0
J             = 1.0
p             = 0.5
q             = 0.5
gJ            = 1.0
print(glsim.PHI(V,theta,Gamma))
print(glsim.weightAdapt_constant(W,A,tauWinv,uW,rhoE,rhoI))
print(glsim.weightAdapt_decrease(W,A,tauWinv,uW,rhoE,rhoI))
print(glsim.weightAdapt_increase(W,A,tauWinv,uW,rhoE,rhoI))
print(glsim.GLNetEIRand_adaptthresh_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIRand_adaptthreshlinear_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIRand_adaptthreshsaturate_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIRand_static_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIMF_adaptthresh_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,W_I,p,q,tauTinv,uT,P_poisson))
print(glsim.GLNetEIMF_adaptthreshsaturate_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,W_I,p,q,tauTinv,uT,P_poisson))
print(glsim.GLNetEIMF_adaptthreshlinear_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,W_I,p,q,tauTinv,uT,P_poisson))
print(glsim.GLNetEIMF_static_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,gJ,p,q,tauTinv,uT,P_poisson))

N              = 10
neuronType     = 'test'
X0_lst         = [0.2,0.5]
K_lst          = [0,4]
is_random_lst  = [True,False]
par_combo      = itertools.product(X0_lst,K_lst,is_random_lst)
for (X0,K,is_random) in par_combo:
    print(glsim.generate_IC_spikes(X0,N,K,neuronType,is_random))



0
[4, 10, 18]
9.999950000172397e-06
[]
[[2 3]]
[[0 1]
 [0 2]
 [0 4]
 [0 7]]
0.020000000000000018
1.0
0.9600000000000009
1.0399999999999991
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, 1.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, 1.0)
 ...  test  IC: starting from the absorbing state (all inactive neurons) because fX0 = 0.0 and X0 = 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 ...  test  IC: starting from the absorbing state (all inactive neurons) because fX0 = 0.0 and X0 = 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 ...  test  IC: starting with  4   random  active neurons regardless of X0
[0. 1. 0. 0. 0. 0. 1. 0. 1. 1.]
 ...  test  IC: starting with  4   sequential  active neurons regardless of X0
[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 ...  test  IC: starting from all active neurons
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 ...  test  IC: starting from all active neurons
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 ...  test  IC: starting with  4   random  active neurons regardless of X0


In [4]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim


pN      = 10#int
qN      = 10#int
g       = 1.0#float
J       = 1.0#float
VE0     = 1.0#float
VE0Std  = 1.0#float
VI0     = 1.0#float
VI0Std  = 1.0#float
XE0     = 1.0#float
fXE0    = 0.5#float
XE0Rand = True#bool
XI0     = 1.0#float
fXI0    = 0.5#float
XI0Rand = True#bool
theta   = 1.0#float
print(glsim.set_MF_network_IC(pN,qN,g,J,VE0,VE0Std,VI0,VI0Std,XE0,fXE0,XE0Rand,XI0,fXI0,XI0Rand,theta))



 ...  excitatory  IC: starting with  5   random  active neurons regardless of X0
 ...  inhibitory  IC: starting with  5   random  active neurons regardless of X0
(array([0.        , 0.075165  , 2.20541526, 0.        , 0.        ,
       0.74691701, 0.1967758 , 2.1170282 , 0.        , 0.        ]), array([1., 0., 0., 1., 1., 0., 0., 0., 1., 1.]), array([1.20465408, 0.        , 1.37278537, 0.85958394, 0.        ,
       0.        , 0.04936094, 0.        , 1.86589712, 0.        ]), array([0., 1., 0., 0., 1., 1., 0., 1., 0., 1.]), 0.5, 0.5, array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 1.0, 1.0)


In [5]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

# 6 of 10 neurons are excitatory; 3 of 5 inputs are excitatory
K_ex = 3
pN   = 6
K    = 5
N    = 10
C = glsim.generate_random_net_fixed_number_of_inputs(K_ex,pN,K,N)

print('C = ')
print(C)

synapticInput = numpy.zeros(N,dtype=numpy.float64)
XE            = numpy.random.randint(0,high=2,size=(pN,))
XI            = numpy.random.randint(0,high=2,size=(N-pN,))
J             = numpy.random.rand(N,K_ex)
W             = numpy.random.rand(N,K-K_ex)
synapticInput = glsim.sumSynpaticInput(synapticInput,K_ex,K,N,XE,XI,J,W,C)
print('synapticInput = ')
print(synapticInput)

sumSynpaticInput_homog = numpy.zeros(N,dtype=numpy.float64)
J                      = 1.0
W                      = 5.0/3.0
sumSynpaticInput_homog = glsim.sumSynpaticInput_homog(synapticInput,K_ex,K,N,XE,XI,J,W,C)
print('sumSynpaticInput_homog = ')
print(sumSynpaticInput_homog)

C = 
[[0 2 5 0 2]
 [0 4 5 0 2]
 [0 2 5 2 3]
 [0 1 2 0 2]
 [2 4 5 2 3]
 [0 2 5 1 3]
 [1 2 5 1 2]
 [0 3 4 2 3]
 [0 2 4 0 2]
 [3 4 5 2 3]]
synapticInput = 
[0.0973746  0.04679473 0.20331875 0.1930168  0.21736083 0.14834096
 0.17015564 0.         0.04754137 0.16456546]
sumSynpaticInput_homog = 
[0.4 0.2 0.4 0.2 0.4 0.4 0.4 0.  0.2 0.2]


In [10]:
import itertools

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim


saveSpikingData_lst = [True,False]
writeOnRun_lst      = [True,False]
pN                  = 6
N                   = 10
XE                  = numpy.random.randint(0,high=2,size=(pN,))
XI                  = numpy.random.randint(0,high=2,size=(N-pN,))
par_combo           = itertools.product(saveSpikingData_lst,writeOnRun_lst)
for (saveSpikingData,writeOnRun) in par_combo:
    print(glsim.get_write_spike_data_functions(saveSpikingData,writeOnRun,XE,XI,pN,N-pN))

d:\Dropbox\p\neuromat\programas\python\balanced_net_gl\modules\GLNetEISimLib_numba.py:514: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  return spkData,write_spk_time,save_spk_time


(array([], shape=(0, 2), dtype=int64), CPUDispatcher(<function write_spk_data at 0x000001E0CA0D0550>), CPUDispatcher(<function save_spk_data_fake at 0x000001E0C7A868B0>))
(array([[0, 0],
       [0, 4],
       [0, 5],
       [0, 7],
       [0, 8]], dtype=int64), CPUDispatcher(<function write_spk_data_fake at 0x000001E0CA2F31F0>), CPUDispatcher(<function save_spk_data at 0x000001E0C78054C0>))
(array([], shape=(0, 2), dtype=int64), CPUDispatcher(<function write_spk_data_fake at 0x000001E0CA2F31F0>), CPUDispatcher(<function save_spk_data_fake at 0x000001E0C7A868B0>))
(array([], shape=(0, 2), dtype=int64), CPUDispatcher(<function write_spk_data_fake at 0x000001E0CA2F31F0>), CPUDispatcher(<function save_spk_data_fake at 0x000001E0C7A868B0>))


In [9]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

fname = 'test.txt'
fid   = glsim.open_file(fname)
glsim.write_spk_data(fid,1,2)
glsim.write_spk_data(fid,1,2)
glsim.write_spk_data(fid,1,2)
glsim.write_spk_data(fid,1,2)
glsim.close_file(fname)

*** writing file  test.txt  during simulation
##################################################
##################################################
##################################################
################################################## file  test.txt  will be printed to stdout
################################################## due to numba limitation
##################################################
##################################################
##################################################
[[[ BEGINNING OF FILE  test.txt ]]]
1 , 2
1 , 2
1 , 2
1 , 2
[[[ END OF FILE  test.txt ]]]
##################################################
##################################################
##################################################
##################################################
##################################################
##################################################
##################################################
#################################