In [1]:
import sys
import argparse
import modules.ioGLNet as io
import modules.GLNetEISimLib_numba as glsim

sys.argv = 'GLNetEI.py -mu 0.0 -Gamma 0.2 -J 10.0 -g 1.4 -Y 1.0 -theta 1.0 -N 1000 -simType aval -p 0.8 -tTotal 10000 -tTrans 3000 -outputFile run/output/glei_aval_G0.2_g1.4_Y1_N1000.mat -nNeuSpikingData 1000'.split(' ')

parser = argparse.ArgumentParser(description='Simulates a GL network of Excitatory/Inhibitory elements in the mean-field level')
parser = io.add_neuron_params(parser)
args = parser.parse_args()

simParam = io.get_sim_param_struct_for_pythran(args)
print(simParam)

structtype(A=73.5, Gamma=0.2, I=1.0, Iext=0.0, J=10.0, K=10, N=1000, Tmax=10000, VE0=0.0, VE0Std=0.0, VI0=0.0, VI0Std=0.0, XE0=0.0, XE0Rand=True, XI0=0.0, XI0Rand=True, Y=1.0, exc_only_dynthresh=False, fXE0=0.5, fXI0=0.5, g=1.4, mu=0.0, nNeuronsSpk=1000, netType='mf', outputFile='run/output/glei_aval_G0.2_g1.4_Y1_N1000.mat', p=0.8, paramCV=0.0, q=0.19999999999999996, rPoisson=0.0, saveSpikingData=False, saveTxtFile=False, simType='aval', spkFileName='', tTrans=3000, tauT=100.0, tauW=100.0, theta=1.0, uT=0.1, uW=0.1, weightDynType='none', writeOnRun=False)


In [2]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

simParam_str, simParam_types = io.simParam_to_str_for_pythran(simParam),io.get_arg_types_dict(simParam)

print(simParam_str)
print(simParam_types)

simParam_str_nb, simParam_types_nb = glsim.convert_simParam_to_numba_dict(simParam_str, simParam_types)

a = glsim.get_system_parameters(simParam_str_nb, simParam_types_nb)
print(a)

{'mu': '0.0', 'Gamma': '0.2', 'J': '10.0', 'g': '1.4', 'Y': '1.0', 'Iext': '0.0', 'A': '73.5', 'tauW': '100.0', 'uW': '0.1', 'tauT': '100.0', 'uT': '0.1', 'theta': '1.0', 'N': '1000', 'p': '0.8', 'rPoisson': '0.0', 'tTrans': '3000', 'VE0': '0.0', 'VI0': '0.0', 'VE0Std': '0.0', 'VI0Std': '0.0', 'XE0': '0.0', 'XI0': '0.0', 'fXE0': '0.5', 'fXI0': '0.5', 'paramCV': '0.0', 'K': '10', 'outputFile': 'run/output/glei_aval_G0.2_g1.4_Y1_N1000.mat', 'netType': 'mf', 'simType': 'aval', 'weightDynType': 'none', 'saveSpikingData': 'False', 'exc_only_dynthresh': 'False', 'writeOnRun': 'False', 'saveTxtFile': 'False', 'I': '1.0', 'XE0Rand': 'True', 'XI0Rand': 'True', 'q': '0.19999999999999996', 'Tmax': '10000', 'nNeuronsSpk': '1000', 'spkFileName': ''}
{'mu': 'float', 'Gamma': 'float', 'J': 'float', 'g': 'float', 'Y': 'float', 'Iext': 'float', 'A': 'float', 'tauW': 'float', 'uW': 'float', 'tauT': 'float', 'uT': 'float', 'theta': 'float', 'N': 'int', 'p': 'float', 'rPoisson': 'float', 'tTrans': 'int', 

In [3]:
import numpy
import itertools

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

print(glsim.get_stim_neuron_index_aval(60))
print(glsim.multvecelem(numpy.array([1,2,3]),numpy.array([4,5,6])))
print(glsim.PoissonProcess_firingprob(1e-5))
print(glsim.save_spk_data_fake(numpy.empty((0,2),dtype=numpy.int64),2,3))
print(glsim.save_spk_data(numpy.empty((0,2),dtype=numpy.int64),2,3))
print(glsim.save_initial_spkdata(numpy.array([0,1,1,0]),numpy.array([1,0,0,1]),4,4))
W             = 1.0
A             = 1.0
tauWinv       = 10.0
uW            = 0.1
rhoE          = 0.4
rhoI          = 0.4
V             = 1.1
X             = 0.0
synapticInput = 0.0
Iext          = 0.0
mu            = 0.0
theta         = 1.0
Gamma         = 0.2
I             = 1.0
P_poisson     = 0.5
tauTinv       = 10.0
uT            = 0.1
W_I           = 1.0
J             = 1.0
p             = 0.5
q             = 0.5
gJ            = 1.0
print(glsim.PHI(V,theta,Gamma))
print(glsim.weightAdapt_constant(W,A,tauWinv,uW,rhoE,rhoI))
print(glsim.weightAdapt_decrease(W,A,tauWinv,uW,rhoE,rhoI))
print(glsim.weightAdapt_increase(W,A,tauWinv,uW,rhoE,rhoI))
print(glsim.GLNetEIRand_adaptthresh_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIRand_adaptthreshlinear_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIRand_adaptthreshsaturate_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIRand_static_iter(V,X,synapticInput,Iext,mu,theta,Gamma,I,P_poisson,tauTinv,uT))
print(glsim.GLNetEIMF_adaptthresh_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,W_I,p,q,tauTinv,uT,P_poisson))
print(glsim.GLNetEIMF_adaptthreshsaturate_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,W_I,p,q,tauTinv,uT,P_poisson))
print(glsim.GLNetEIMF_adaptthreshlinear_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,W_I,p,q,tauTinv,uT,P_poisson))
print(glsim.GLNetEIMF_static_iter(V,X,rhoE,rhoI,Iext,mu,theta,J,Gamma,I,gJ,p,q,tauTinv,uT,P_poisson))

N              = 10
neuronType     = 'test'
X0_lst         = [0.2,0.5]
K_lst          = [0,4]
is_random_lst  = [True,False]
par_combo      = itertools.product(X0_lst,K_lst,is_random_lst)
for (X0,K,is_random) in par_combo:
    print(glsim.generate_IC_spikes(X0,N,K,neuronType,is_random))



45
[4, 10, 18]
9.999950000172397e-06
[]
[[2 3]]
[[0 1]
 [0 2]
 [0 4]
 [0 7]]
0.020000000000000018
1.0
0.9600000000000009
1.0399999999999991
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 0.0, 1.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, -9.0)
(1.0, 1.0, 1.0)
 ...  test  IC: starting from the absorbing state (all inactive neurons) because fX0 = 0.0 and X0 = 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 ...  test  IC: starting from the absorbing state (all inactive neurons) because fX0 = 0.0 and X0 = 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 ...  test  IC: starting with  4   random  active neurons regardless of X0
[0. 0. 1. 0. 1. 1. 0. 0. 0. 1.]
 ...  test  IC: starting with  4   sequential  active neurons regardless of X0
[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 ...  test  IC: starting from all active neurons
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 ...  test  IC: starting from all active neurons
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 ...  test  IC: starting with  4   random  active neurons regardless of X0

In [4]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim


pN      = 10#int
qN      = 10#int
g       = 1.0#float
J       = 1.0#float
VE0     = 1.0#float
VE0Std  = 1.0#float
VI0     = 1.0#float
VI0Std  = 1.0#float
XE0     = 1.0#float
fXE0    = 0.5#float
XE0Rand = True#bool
XI0     = 1.0#float
fXI0    = 0.5#float
XI0Rand = True#bool
theta   = 1.0#float
print(glsim.set_MF_network_IC(pN,qN,g,J,VE0,VE0Std,VI0,VI0Std,XE0,fXE0,XE0Rand,XI0,fXI0,XI0Rand,theta))



 ...  excitatory  IC: starting with  5   random  active neurons regardless of X0
 ...  inhibitory  IC: starting with  5   random  active neurons regardless of X0
(array([0.        , 0.        , 0.64294353, 0.        , 0.23076489,
       3.29910392, 0.        , 2.5903559 , 0.        , 0.16367754]), array([1., 1., 0., 1., 0., 0., 1., 0., 1., 0.]), array([0.68796988, 0.        , 0.        , 2.81675479, 1.36013458,
       1.11956097, 0.        , 0.6253277 , 0.        , 0.        ]), array([0., 1., 1., 0., 0., 0., 1., 0., 1., 1.]), 0.5, 0.5, array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 1.0, 1.0)


In [5]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

# 6 of 10 neurons are excitatory; 3 of 5 inputs are excitatory
K_ex = 3
pN   = 6
K    = 5
N    = 10
C = glsim.generate_random_net_fixed_number_of_inputs(K_ex,pN,K,N)

print('C = ')
print(C)

synapticInput = numpy.zeros(N,dtype=numpy.float64)
XE            = numpy.random.randint(0,high=2,size=(pN,))
XI            = numpy.random.randint(0,high=2,size=(N-pN,))
J             = numpy.random.rand(N,K_ex)
W             = numpy.random.rand(N,K-K_ex)
synapticInput = glsim.sumSynpaticInput(synapticInput,K_ex,K,N,XE,XI,J,W,C)
print('synapticInput = ')
print(synapticInput)

sumSynpaticInput_homog = numpy.zeros(N,dtype=numpy.float64)
J                      = 1.0
W                      = 5.0/3.0
sumSynpaticInput_homog = glsim.sumSynpaticInput_homog(synapticInput,K_ex,K,N,XE,XI,J,W,C)
print('sumSynpaticInput_homog = ')
print(sumSynpaticInput_homog)

C = 
[[0 1 3 0 3]
 [0 1 4 1 2]
 [1 3 4 0 2]
 [0 2 4 1 3]
 [0 1 2 0 2]
 [1 2 5 0 2]
 [2 3 4 1 2]
 [0 4 5 0 3]
 [0 1 2 2 3]
 [0 2 3 0 3]]
synapticInput = 
[ 0.01116309  0.16280844  0.24880665 -0.14860458  0.0819409   0.18868627
  0.10888199 -0.04931248  0.09857736 -0.05758705]
sumSynpaticInput_homog = 
[-0.26666667 -0.13333333  0.06666667 -0.66666667 -0.13333333  0.06666667
 -0.13333333 -0.46666667 -0.13333333 -0.46666667]


In [6]:
import itertools

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim


saveSpikingData_lst = [True,False]
writeOnRun_lst      = [True,False]
pN                  = 6
N                   = 10
XE                  = numpy.random.randint(0,high=2,size=(pN,))
XI                  = numpy.random.randint(0,high=2,size=(N-pN,))
par_combo           = itertools.product(saveSpikingData_lst,writeOnRun_lst)
for (saveSpikingData,writeOnRun) in par_combo:
    print(glsim.get_write_spike_data_functions(saveSpikingData,writeOnRun,XE,XI,pN,N-pN))

(array([], shape=(0, 2), dtype=int64), CPUDispatcher(<function write_spk_data at 0x7dc7f45ada20>), CPUDispatcher(<function save_spk_data_fake at 0x7dc7cdb2b2e0>))
(array([[0, 0],
       [0, 2],
       [0, 4],
       [0, 8]]), CPUDispatcher(<function write_spk_data_fake at 0x7dc7cdb28790>), CPUDispatcher(<function save_spk_data at 0x7dc7cdb2a320>))
(array([], shape=(0, 2), dtype=int64), CPUDispatcher(<function write_spk_data_fake at 0x7dc7cdb28790>), CPUDispatcher(<function save_spk_data_fake at 0x7dc7cdb2b2e0>))
(array([], shape=(0, 2), dtype=int64), CPUDispatcher(<function write_spk_data_fake at 0x7dc7cdb28790>), CPUDispatcher(<function save_spk_data_fake at 0x7dc7cdb2b2e0>))


/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:516: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  return spkData,write_spk_time,save_spk_time


In [7]:
del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

fname = 'test.txt'
fid   = glsim.open_file(fname)
glsim.write_spk_data(fid,1,2)
glsim.write_spk_data(fid,1,2)
glsim.write_spk_data(fid,1,2)
glsim.write_spk_data(fid,1,2)
glsim.close_file(fname)

*** writing file  test.txt  during simulation
##################################################
##################################################
##################################################
################################################## file  test.txt  will be printed to stdout
################################################## due to numba limitation
##################################################
##################################################
##################################################
[[[ BEGINNING OF FILE  test.txt ]]]
1 , 2
1 , 2
1 , 2
1 , 2
[[[ END OF FILE  test.txt ]]]
##################################################
##################################################
##################################################
##################################################
##################################################
##################################################
##################################################
#################################

In [8]:
import itertools

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

simType_lst       = parser._option_string_actions['-simType'].choices
weightDynType_lst = parser._option_string_actions['-weightDynType'].choices

exc_only_dynthresh_lst     = [ True, False ]
par_combo = itertools.product(simType_lst,exc_only_dynthresh_lst)
for (simType,exc_only_dynthresh) in par_combo:
    print(glsim.get_MFNet_neuron_state_iter(simType,exc_only_dynthresh))

for simType in simType_lst:
    print(glsim.get_MFNet_stimulus_func(simType))

q_lst     = [ 0.0, 0.5 ]
par_combo = itertools.product(simType_lst,weightDynType_lst,q_lst)
for (simType,weightDynType,q) in par_combo:
    print(glsim.get_MFNet_synaptic_weight_iter(weightDynType,simType,q))


/home/mgirardi/pylocal/lib/python3.10/site-packages/numba/core/utils.py:661: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:576: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  return GLNetEIMF_E_iter,GLNetEIMF_I_iter


 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIMF_static_iter at 0x7dc7f45ae3b0>), CPUDispatcher(<function GLNetEIMF_static_iter at 0x7dc7f45ae3b0>))
 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIMF_static_iter at 0x7dc7f45ae3b0>), CPUDispatcher(<function GLNetEIMF_static_iter at 0x7dc7f45ae3b0>))
 ... choosing neuron wiht: 
 ....... NONLINEAR adaptive threshold (multiplicative noise)
 ....... INHIBITORY neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIMF_adaptthresh_iter at 0x7dc7f45afac0>), CPUDispatcher(<function GLNetEIMF_static_iter at 0x7dc7f45ae3b0>))
 ... choosing neuron wiht: 
 ....... NONLINEAR adaptive threshold (multiplicative noise)
(CPUDispatcher(<function GLNetEIMF_adaptthresh_iter at 0x7dc7f45afac0>), CPUDispatcher(<function GLNetEIMF_adaptthresh_iter at 0x7dc7f45afac0>))
 ... choosing neuron wiht: 
 ....... NONLINEAR adaptive threshold (m

/home/mgirardi/pylocal/lib/python3.10/site-packages/numba/core/utils.py:661: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:594: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  return weightAdapt_iter


In [9]:
import itertools

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

simType_lst       = parser._option_string_actions['-simType'].choices
weightDynType_lst = parser._option_string_actions['-weightDynType'].choices

exc_only_dynthresh_lst     = [ True, False ]
par_combo = itertools.product(simType_lst,exc_only_dynthresh_lst)
for (simType,exc_only_dynthresh) in par_combo:
    print(glsim.get_RandomNet_neuron_state_iter(simType,exc_only_dynthresh))

for simType in simType_lst:
    print(glsim.get_RandomNet_stimulus_func(simType))


 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>), CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>))
 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>), CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>))
 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>), CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>))
 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>), CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>))
 ... choosing neuron wiht: 
 ....... neurons will not adapt thresholds!
(CPUDispatcher(<function GLNetEIRand_static_iter at 0x7dc7fab8e170>), CPUDispatcher(

/home/mgirardi/pylocal/lib/python3.10/site-packages/numba/core/utils.py:661: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:541: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  return GLNetEIRand_E_iter,GLNetEIRand_I_iter
/home/mgirardi/pylocal/lib/python3.10/site-packages/numba/core/utils.py:661: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:551: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  return get_external_stimulus,get_stim_neuron_index


In [10]:
import sys
import argparse
import modules.ioGLNet as io
import modules.GLNetEISimLib_numba as glsim

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

sys.argv = 'GLNetEI.py -rPoisson 0.000001000000000 -netType mf -p 1.0 -mu 0.0 -Gamma 0.2 -J 5.0 -Y 1.0 -tauT 100 -uT 0.1 -theta 1.0 -N 100 -simType adaptthresh -tTotal 1000 -tTrans 0 -outputFile test_sim_mf.txt -nNeuSpikingData 100 -writeOnRun -saveSpikingData'.split(' ')

parser = argparse.ArgumentParser(description='Simulates a GL network of Excitatory/Inhibitory elements in the mean-field level')
parser = io.add_neuron_params(parser)
args = parser.parse_args()

simParam = io.get_sim_param_struct_for_pythran(args)
print(simParam)


simParam_numba,paramType_numba = glsim.convert_simParam_to_numba_dict(io.simParam_to_str_for_pythran(simParam),io.get_arg_types_dict(simParam))

rhoE,rhoI,spkData,excSynCurrent,inhSynCurrent,g_data,Y_data = glsim.RunSimulation_GLNetEIMF(simParam_numba,paramType_numba)


structtype(A=73.5, Gamma=0.2, I=1.0, Iext=0.0, J=5.0, K=10, N=100, Tmax=1000, VE0=0.0, VE0Std=0.0, VI0=0.0, VI0Std=0.0, XE0=0.0, XE0Rand=True, XI0=0.0, XI0Rand=True, Y=1.0, exc_only_dynthresh=False, fXE0=0.5, fXI0=0.5, g=3.0, mu=0.0, nNeuronsSpk=100, netType='mf', outputFile='glexc_adaptthresh_tau100_u0.1_J5.0_r0.000001.txt', p=1.0, paramCV=0.0, q=0.0, rPoisson=1e-06, saveSpikingData=True, saveTxtFile=False, simType='adaptthresh', spkFileName='', tTrans=0, tauT=100.0, tauW=100.0, theta=1.0, uT=0.1, uW=0.1, weightDynType='none', writeOnRun=True)


/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:219: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  GLNetEIMF_E_iter,GLNetEIMF_I_iter = get_MFNet_neuron_state_iter(simType,exc_only_dynthresh)
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:222: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  weightAdapt_iter = get_MFNet_synaptic_weight_iter(weightDynType,simType,q)
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:225: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  get_external_stimulus = get_MFNet_stimulus_func(simType)
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:269: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  spkData,write_spk_time,s

 ... forcing the CV of all parameters to be zero (homogeneous network), since parameter variability is not implemented yet
 ... choosing neuron wiht: 
 ....... NONLINEAR adaptive threshold (multiplicative noise)
 ... forcing constant inhibitory W because simType == adaptthresh
 ...  excitatory  IC: starting with  50   random  active neurons regardless of X0
 ...  inhibitory  IC: starting from the absorbing state (all inactive neurons) because fX0 = 0.0 and X0 = 0.0
*** writing file    during simulation
*** writing file    during simulation
##################################################
##################################################
##################################################
################################################## file    will be printed to stdout
################################################## due to numba limitation
##################################################
##################################################
#######################################

In [11]:
import sys
import argparse
import modules.ioGLNet as io
import modules.GLNetEISimLib_numba as glsim

del sys.modules['modules.GLNetEISimLib_numba']
del glsim
import modules.GLNetEISimLib_numba as glsim

sys.argv = 'GLNetEI.py -rPoisson 0.000001000000000 -netType random -p 1.0 -mu 0.0 -Gamma 0.2 -J 5.0 -Y 1.0 -tauT 100 -uT 0.1 -theta 1.0 -N 100 -simType adaptthresh -tTotal 1000 -tTrans 0 -outputFile test_sim_random.txt -nNeuSpikingData 100 -writeOnRun -saveSpikingData'.split(' ')

parser = argparse.ArgumentParser(description='Simulates a GL network of Excitatory/Inhibitory elements in the mean-field level')
parser = io.add_neuron_params(parser)
args = parser.parse_args()

simParam = io.get_sim_param_struct_for_pythran(args)
print(simParam)


simParam_numba,paramType_numba = glsim.convert_simParam_to_numba_dict(io.simParam_to_str_for_pythran(simParam),io.get_arg_types_dict(simParam))

rhoE,rhoI,spkData,excSynCurrent,inhSynCurrent,g_data,Y_data = glsim.RunSimulation_GLNetEIRand(simParam_numba,paramType_numba)


structtype(A=73.5, Gamma=0.2, I=1.0, Iext=0.0, J=5.0, K=10, N=100, Tmax=1000, VE0=0.0, VE0Std=0.0, VI0=0.0, VI0Std=0.0, XE0=0.0, XE0Rand=True, XI0=0.0, XI0Rand=True, Y=1.0, exc_only_dynthresh=False, fXE0=0.5, fXI0=0.5, g=3.0, mu=0.0, nNeuronsSpk=100, netType='random', outputFile='glexc_adaptthresh_tau100_u0.1_J5.0_r0.000001.txt', p=1.0, paramCV=0.0, q=0.0, rPoisson=1e-06, saveSpikingData=True, saveTxtFile=False, simType='adaptthresh', spkFileName='', tTrans=0, tauT=100.0, tauW=100.0, theta=1.0, uT=0.1, uW=0.1, weightDynType='none', writeOnRun=True)


/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:105: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  GLNetEIRand_E_iter, GLNetEIRand_I_iter = get_RandomNet_neuron_state_iter(simType,exc_only_dynthresh)
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:108: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  get_external_stimulus,get_stim_neuron_index = get_RandomNet_stimulus_func(simType)
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:148: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  rhoETemp,rhoITemp,thetaMean,W_I,VE,XE,VI,XI,thetaE,thetaI = run_transient_GLNetEIRand(simType,exc_only_dynthresh,VE,XE,VI,XI,tTrans,rhoETemp,rhoITemp,pN,qN,pN_fl,qN_fl,P_firing_poisson,Iext,mu,theta,Gamma,I,synapticInput,J,W_I,C,KE,K,A,tauTinv,tauWinv,

 ... forcing the CV of all parameters to be zero (homogeneous network), since parameter variability is not implemented yet
 ... choosing neuron wiht: 
 ....... NONLINEAR adaptive threshold (multiplicative noise)
 ...  excitatory  IC: starting with  50   random  active neurons regardless of X0
 ...  inhibitory  IC: starting from the absorbing state (all inactive neurons) because fX0 = 0.0 and X0 = 0.0
*** writing file    during simulation
*** writing file    during simulation
##################################################
##################################################
##################################################
################################################## file    will be printed to stdout
################################################## due to numba limitation
##################################################
##################################################
##################################################
[[[ BEGINNING OF FILE   ]]]
1 , 0
1 , 5
1 , 7
1 , 12
1

In [12]:
!python -OO GLNetEI.py -rPoisson 0.000001000000000 -netType mf -p 1.0 -mu 0.0 -Gamma 0.2 -J 5.0 -Y 1.0 -tauT 100 -uT 0.1 -theta 1.0 -N 100 -simType adaptthresh -tTotal 1000 -tTrans 0 -outputFile test_sim_mf.txt -nNeuSpikingData 100 -writeOnRun -saveSpikingData

/home/mgirardi/pylocal/lib/python3.10/site-packages/pycparser/c_parser.py:18: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly
  class CParser(PLYParser):
* Setting input parameters ...
A=73.5
Gamma=0.2
Iext=0.0
J=5.0
K=10
N=100
N_rec_Exc=100
VE0=0.0
VE0Std=0.0
VI0=0.0
VI0Std=0.0
W=5.0
XE0=0.0
XI0=0.0
Y=1.0
exc_only_dynthresh=False
fXE0=0.5
fXI0=0.5
g=3.0
h=0.0
mu=0.0
nNeuSpikingData=100
netType='mf'
noXE0Rand=False
noXI0Rand=False
outputFile='test_sim_mf.txt'
p=1.0
paramCV=0.0
rPoisson=1e-06
saveSpikingData=True
saveTxtFile=False
simType='adaptthresh'
tTotal=1000
tTrans=0
tauT=100.0
tauW=100.0
theta=1.0
uT=0.1
uW=0.1
weightDynType='none'
writeOnRun=True
* Running simulation...
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:219: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  GLNetEIMF_E_iter,GLNetEIMF_I_iter = get_MFNet_neuron_state_iter(simType,exc_only_dynthresh)
/

In [13]:
!python -OO GLNetEI.py -rPoisson 0.000001000000000 -netType random -p 1.0 -mu 0.0 -Gamma 0.2 -J 5.0 -Y 1.0 -tauT 100 -uT 0.1 -theta 1.0 -N 100 -simType adaptthresh -tTotal 1000 -tTrans 0 -outputFile test_sim_random.txt -nNeuSpikingData 100 -writeOnRun -saveSpikingData

/home/mgirardi/pylocal/lib/python3.10/site-packages/pycparser/c_parser.py:18: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly
  class CParser(PLYParser):
* Setting input parameters ...
A=73.5
Gamma=0.2
Iext=0.0
J=5.0
K=10
N=100
N_rec_Exc=100
VE0=0.0
VE0Std=0.0
VI0=0.0
VI0Std=0.0
W=5.0
XE0=0.0
XI0=0.0
Y=1.0
exc_only_dynthresh=False
fXE0=0.5
fXI0=0.5
g=3.0
h=0.0
mu=0.0
nNeuSpikingData=100
netType='random'
noXE0Rand=False
noXI0Rand=False
outputFile='test_sim_random.txt'
p=1.0
paramCV=0.0
rPoisson=1e-06
saveSpikingData=True
saveTxtFile=False
simType='adaptthresh'
tTotal=1000
tTrans=0
tauT=100.0
tauW=100.0
theta=1.0
uT=0.1
uW=0.1
weightDynType='none'
writeOnRun=True
* Running simulation...
/home/mgirardi/Dropbox/p/neuromat/programas/python/balanced_net_gl/modules/GLNetEISimLib_numba.py:105: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  GLNetEIRand_E_iter, GLNetEIRand_I_iter = get_RandomNet_neuron_state_iter(simType,exc_